services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=taskflow_user
      - POSTGRES_PASSWORD=Sofi2009
      - POSTGRES_DB=taskflow_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U taskflow_user -d taskflow_db']
      interval: 10s
      timeout: 5s
      retries: 5
  
  # Redis para caché (lo usaremos después)
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: diegoleteliers10@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Aline2702_
    ports:
      - "80:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:
